//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarineDataSheet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datum
    {
        public int Laskuri { get; set; }
        public bool STD { get; set; }
        public string Datasivun_numero { get; set; }
        public string Datasheet_revision { get; set; }
        public Nullable<System.DateTime> Valid_from { get; set; }
        public string Datasheet_status { get; set; }
        public string Code { get; set; }
        public string Datasheet_created_by { get; set; }
        public string Model_No { get; set; }
        public Nullable<double> Maximum_working_pressure_barg { get; set; }
        public string Cooling { get; set; }
        public string C1_Voltage { get; set; }
        public string C1_Frequency { get; set; }
        public string C1_Starting_type { get; set; }
        public string C2_Voltage { get; set; }
        public string C2_Frequency { get; set; }
        public string C2_Starting_type { get; set; }
        public string Normal_working_pressure_barg { get; set; }
        public Nullable<double> Capacity_at_normal_working_pressure_m_min { get; set; }
        public Nullable<double> Capacity_at_normal_working_pressure_m_min_75 { get; set; }
        public Nullable<double> Capacity_at_normal_working_pressure_m_min_50 { get; set; }
        public Nullable<double> Capacity_at_normal_working_pressure_m_min_25 { get; set; }
        public Nullable<double> Capacity_at_normal_working_pressure_m_min_min { get; set; }
        public string Volumetric_efficiency { get; set; }
        public string Air_end_volume_per_revolution { get; set; }
        public Nullable<double> Shaft_power_at_normal_working_pressure_kW { get; set; }
        public Nullable<double> Shaft_power_at_normal_working_pressure_kW_75 { get; set; }
        public Nullable<double> Shaft_power_at_normal_working_pressure_kW_50 { get; set; }
        public Nullable<double> Shaft_power_at_normal_working_pressure_kW_25 { get; set; }
        public Nullable<double> Shaft_power_at_normal_working_pressure_kW_min { get; set; }
        public string Specific_power_consumption_kW_m_min { get; set; }
        public string Extra_capacity { get; set; }
        public Nullable<double> Minimum_working_pressure_barg { get; set; }
        public string Frequency_min { get; set; }
        public string Frequency_max { get; set; }
        public string Transmission { get; set; }
        public Nullable<double> Transmission_Gear_i { get; set; }
        public Nullable<int> Motor_pulley { get; set; }
        public Nullable<int> Air_end_pulley { get; set; }
        public Nullable<double> Maximum_ambient_temperature_C { get; set; }
        public Nullable<double> Compressed_air_temperature_above_cooling_medium_temperature_C { get; set; }
        public Nullable<double> Cooling_air_flow_m_s { get; set; }
        public Nullable<double> Cooling_air_flow_m_s_water_cooled { get; set; }
        public Nullable<double> Maximum_cooling_air_pressure_drop__Pa_ { get; set; }
        public Nullable<double> Water_in_C_Fresh_water_cooled { get; set; }
        public Nullable<double> Water_out_C_Fresh_water_cooled { get; set; }
        public Nullable<double> Water_in_C_Sea_water_cooled { get; set; }
        public Nullable<double> Water_out_C_Sea_water_cooled { get; set; }
        public string Extra_factor_for_water_flow_at_60_humidity_fresh { get; set; }
        public Nullable<double> Minimum_water_inlet_pressure_with_zero_back_bar_MPa_Serial { get; set; }
        public Nullable<double> Minimum_water_inlet_pressure_with_zero_ba_bar_MPa_Parallel { get; set; }
        public Nullable<double> Minimum_water_inlet_pressure_with_zero_back_Serial_sea { get; set; }
        public Nullable<double> Minimum_water_inlet_pressure_with_zero_back_Parallel_sea { get; set; }
        public Nullable<double> Minimum_water_inlet_pressure_with_zero_back_bar_MPa_Oil { get; set; }
        public Nullable<double> Minimum_water_inlet_pressure_with_zero_back_bar_MPa_After { get; set; }
        public Nullable<double> Maximum_inlet_pressure_barg { get; set; }
        public string Water_in_out_T2_T3 { get; set; }
        public string Heat_dissipation_kW_EA { get; set; }
        public string Heat_dissipation_kW_EW { get; set; }
        public Nullable<double> Main_motor_F_class_IP_55_kW { get; set; }
        public Nullable<double> Main_motor_max_power { get; set; }
        public string Main_motor_protection_details { get; set; }
        public string Main_motor_temperature_rise { get; set; }
        public Nullable<double> Speed_of_rotation_rpm { get; set; }
        public Nullable<double> Speed_of_rotation_rpm_min { get; set; }
        public Nullable<double> Motor_cos_fii { get; set; }
        public Nullable<double> Motor_efficiency { get; set; }
        public Nullable<double> Fan_motor_kW_EA { get; set; }
        public Nullable<double> Fan_motor_kW_EW { get; set; }
        public string Speed_of_rotation_rpm__fan_motor { get; set; }
        public string Voltage_tolerance { get; set; }
        public string Hydraulic_main_motor { get; set; }
        public string Hydraulic_motor_speed_of_rotation_Max { get; set; }
        public string Hydraulic_motor_speed_of_rotation_Min { get; set; }
        public string Hydraulic_oil_flow_l_min { get; set; }
        public string Hydraulic_oil_flow_l_min_min { get; set; }
        public string Hydraulic_oil_pressure_bar { get; set; }
        public string Hydraulic_oil_pressure_bar_min { get; set; }
        public string Fuse_max_1_Jännite_A { get; set; }
        public string Fuse_max_2_Jännite_A { get; set; }
        public string Starting_current_Ia_In_DOL_YD_SOFT_START { get; set; }
        public string Control_voltage_V { get; set; }
        public Nullable<double> Oil_quantity_I { get; set; }
        public Nullable<double> Oil_quantity_EA_I { get; set; }
        public Nullable<double> Oil_content_mg_m { get; set; }
        public string Air_outlet_T1 { get; set; }
        public string Air_outlet_T1_water_cooled { get; set; }
        public string Condensate_drain_T4 { get; set; }
        public string Pressure_Level_LpA_without_canopy_EA { get; set; }
        public string Pressure_Level_LpA_without_canopy_EW { get; set; }
        public string Pressure_Level_LpA_with_NOVOX_canopy_EA { get; set; }
        public string Pressure_Level_LpA_with_NOVOX_canopy_EW { get; set; }
        public string Uncertainty_Kpa_Kwa { get; set; }
        public string Weight_without_canopy { get; set; }
        public string Weight_with_NOVOX_canopy { get; set; }
        public string Weight_with_NOVOX_canopy_EA { get; set; }
        public string General_arrangement_drawing_SW { get; set; }
        public string General_arrangement_drawing_FW { get; set; }
        public string General_arrangement_drawing_EA { get; set; }
        public string General_arrangement_drawing_with_NOVOX_canopy_EA { get; set; }
        public string General_arrangement_drawing_with_NOVOX_canopy_EW { get; set; }
        public string General_arrangement_drawing_with_NOVOX_canopy_EW_SW { get; set; }
        public string Cable_gland__Power { get; set; }
        public string Cable_gland_Alarm_Signal { get; set; }
        public string Lisätietoja { get; set; }
        public string Suunnittelun_kommentit { get; set; }
    }
}
