//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarineDataSheet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jälkijäähdytinteho_korjauskerroin
    {
        public int Tunniste { get; set; }
        public Nullable<double> Maximum_working_pressure__barg_ { get; set; }
        public string Korjauskerroin { get; set; }
    }
}
