//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarineDataSheet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarinedataEntities : DbContext
    {
        public MarinedataEntities()
            : base("name=MarinedataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Datum> Data { get; set; }
        public virtual DbSet<Jälkijäähdytinteho_korjauskerroin> Jälkijäähdytinteho_korjauskerroin { get; set; }

        public System.Data.Entity.DbSet<MarineDataSheet.Models.Datasheet> Datasheets { get; set; }
    }
}
